apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-3-tier

spec:
  replicas: 1
  selector:
    matchLabels:
     app: gitops
    
  template:
    metadata:
      labels: 
        app: gitops
  
    spec:
      containers:
      - name: gitops
        image: nirmal08/ci-3-tier:latest
        ports:
        - containerPort: 80
