apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: backend-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/NirmalMishra08/ci-3-tier.git
    targetRevision: dev
    path: helm/gitops

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true